### ISSUE TITLE
How to check subscription state in Android billing?

### ISSUE THREAD

**Issue by Mahadev-code** [moisoni97/google-inapp-billing#11]
I have some app, which have subscription. User can buy subs, but how I can check is subs currently active.

**Comment by mkhan9047** [comment]
@moisoni97 Can you please give this answer, I am also facing the same issue. Very important 🙏🏽

**Comment by mkhan9047** [comment]
@Mahadev-code did you find the solution?

**Comment by mkhan9047** [comment]
@Mahadev-code 
Here is the solution I got, Hope it will help you. Thanks

@Override
            public void onPurchasedProductsFetched(@NonNull List<PurchaseInfo> purchases) {
                if(purchases.size() > 0){
                    if(!purchases.get(0).isAutoRenewing()){
                        runOnUiThread(() -> {
                            Toasty.info(MainActivity.this, "You canceled subscription!").show();
                            SharedPrefUtils.INSTANCE.write(Constants.PreferenceKeys.IS_SUBSCRIBED, false);
                        });
                    }
                }
            }

**Comment by moisoni97** [comment]
I don't have time now but I will come back (maybe) tomorrow (or when I'll have time) with the correct solution.
@mkhan9047 your code is wrong on so many levels, don't use that.

**Comment by moisoni97** [comment]
According to [this](https://developer.android.com/google/play/billing/subscriptions#expirations), expired subscriptions are no longer returned by `queryPurchasesAsync`. This means that `onPurchasedProductsFetched` callback will no longer contain the expired subscription id in its list.
To remove the entitlement for the expired subscription you can do something like this:

```
@Override
public void onPurchasedProductsFetched(@NonNull @NotNull List<PurchaseInfo> purchases) {
        String sku;

        for (PurchaseInfo purchaseInfo : purchases) {
              sku = purchaseInfo.getSku();
                    
              if (sku.contains("subscription_id")) {
                   //TODO - grand user entitlement
              } else {
                    //TODO - remove user entitlement
              }
         }
}
```

**Comment by Mahadev-code** [comment]
Thank you.

**Comment by moisoni97** [comment]
The method I provided above to check the `subscription state` is valid but it doesn't work on the current version of the library (`1.0.5`) because the `onPurchasedProductsFetched` callback is not called with an empty list, see #10 for more details.

You can implement the logic in your project as described above and then when the issue is fixed just update the library version.
