### ISSUE TITLE
Granting title to the product to the user before the purchase is confirmed.

### ISSUE THREAD

**Issue by franciscowilton** [moisoni97/google-inapp-billing#14]
First of all, I'm new to the subject of programming, I managed to implement in-app-purchase almost successfully, but I'm facing some problems:

I have a problem that when I make a test purchase that will be denied after a few minutes, it already calls the OnProductPurchase event and gives the user the title of the product.  How to solve?
I would like to verify that the user has actually purchased by validating the purchase information before granting entitlement.

https://user-images.githubusercontent.com/60080154/129499718-cf5149e3-a6d4-40d1-a15d-78c0f9729924.mp4

Also would you like to implement queryPurchasesAsync() is the library compatible?  I didn't find any information in the README

Oh, one more thing, Lucky Patcher makes the purchase easily with just one click, does anyone have an efficient system against that?

Thank you very much in advance.

**Comment by DNAMobileApplications** [comment]
Hey can you help me with the logic, I have to update my billing for a few apps but cannot seem to get this library to initiate purchases.  I can get the ID information like prices and descriptions but when I implement .purchase it doesn't do anything. 

Thank you

**Comment by moisoni97** [comment]
@franciscowilton to solve this you need to grand user entitlement in `onPurchaseAcknowledged` callback as I said [here](https://github.com/moisoni97/google-inapp-billing#usage). If everything goes well with the purchase the callback will be called immediately, but if the purchase is `pending` (like you described above) the callback will be triggered after the user restarts the app or wait long enough until the payment completes. For this situation, I have added in `onBillingError` callback the `ACKNOWLEDGE_WARNING` error type where you can inform the user that it may take a while until the purchase completes and to come back layer to receive their purchase (see README, everything is described there).

`queryPurchasesAsync()` is called by the library, check the source code.

'Lucky Patcher' can crack any android app. To solve this problem you need to implement a server-side verification...

@DNAMobileApplications I have responded to your other 'issue' please provide the necessary info there.

**Comment by franciscowilton** [comment]
Thank you very much for the feedback, you managed to clear almost all my doubts, however, regarding the verification with my server to avoid fraudulent purchases, what would be the data used in this verification?  And how to get it after purchase?

**Comment by DNAMobileApplications** [comment]
Hey thank you for responding!

  Now I'm getting a message saying "Trying to subscribe" which I've never
had before.  I attached a screenshot to this email, I really hope to get
this figured out before the weekend I'm so stumped at this point.

**Comment by DNAMobileApplications** [comment]
![Screenshot_20210819-165810_Thermal Print Images](https://user-images.githubusercontent.com/89114569/130143509-37957783-8523-4694-be4f-9f77f20d0f7d.jpg)

**Comment by DNAMobileApplications** [comment]
Oh wait nevermind I forgot I put a toast on my button this morning for testing purposes to make sure it was calling onClick event correctly lol.

**Comment by moisoni97** [comment]
@franciscowilton I have no idea how to implement server-side verification, I never bothered to do it for my apps. Do a search on Google and surely you will find something.

@DNAMobileApplications LOL. Also please add your comments on the other issue you have created because it's more related to that.
