### ISSUE TITLE
Card is declined

### ISSUE THREAD

**Issue by renzard** [moisoni97/google-inapp-billing#2]
In the case the card is declined we are not able to handle the error

**Comment by moisoni97** [comment]
`Google Billing API` doesn't provide any error callback when the card is declined (check here the list to see all possible response codes and their meaning: https://android-doc.github.io/google/play/billing/billing_reference.html)

In `onBillingError` you can get either the `ErrorType` which is provided by this library for convenience or you can get the official `Google Response Codes` like this:

```
int responseCode = response.getResponseCode();
String responseMessage = response.getMessage();

Log.d("BillingConnector", "Response code: " + responseCode);
Log.d("BillingConnector", "Response debug message: " + responseMessage);
```

**Comment by renzard** [comment]
thank you for your quick response you are very helpful.
