### ISSUE TITLE
Using coreLibraryDesugaringEnabled causes crash when my app starts

### ISSUE THREAD

**Issue by PaulGene** [moisoni97/google-inapp-billing#20]
Hi,

I'm just wondering what is causing the coreLibraryDesugaringEnabled requirement for older devices? Is it because you are using java.util.List.stream?

Thanks

**Comment by moisoni97** [comment]
Yes, `coreLibraryDesugaringEnabled` is needed for `java.util.List.stream`. If your app crashes because of this maybe you haven't integrated it the right way, take a look at the README, or [here](https://developer.android.com/studio/write/java8-support#library-desugaring).

**Comment by PaulGene** [comment]
Thank you, I was definitely integrating properly... But no worries I've recoded the stream parts so it's no longer needed. The extension is working great, thank you for releasing it to the public!
