### ISSUE TITLE
bad class

### ISSUE THREAD

**Issue by idrisyildiz7** [moisoni97/google-inapp-billing#26]
bad class file: /private/var/root/.gradle/caches/transforms-2/files-2.1/df4279a49e79bf63c6c455bff6f5285e/jetified-google-inapp-billing-1.0.6-api.jar(games/moisoni/google_iab/BillingConnector.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.

**Comment by moisoni97** [comment]
Context?
