### ISSUE TITLE
Error in classes_proguard.jar

### ISSUE THREAD

**Issue by franciscowilton** [moisoni97/google-inapp-billing#29]
I recently updated the lib to version 1.0.6 and I am getting an error building with proguard, the error is as follows: Compilation failed to complete, origin: /storage/emulated/0/.sketchware/mysc/601/bin/classes_proguard.jar

In version 1.0.5, proguard worked normally.

What could be happening?

**Comment by moisoni97** [comment]
Hi,
Have you solved it? 
For me, it's compiling.

**Comment by franciscowilton** [comment]
> Hi, Have you solved it? For me, it's compiling.

I still can't solve.

**Comment by moisoni97** [comment]
It's strange because I haven't changed anything related to proguard, for me it seems more like a generic problem, not something related to the library itself...
I am sure you will find the solution on `stackoverflow`.

Try to add this to your proguard:
```
-keep class com.android.vending.billing.** //I think this may be skipped because it's already added in the library in consumer proguard file
-keep class com.android.billingclient.api.**
```

**Comment by franciscowilton** [comment]
> It's strange because I haven't changed anything related to proguard, for me it seems more like a generic problem, not something related to the library itself... I am sure you will find the solution on `stackoverflow`.
> 
> Try to add this to your proguard:
> 
> ```
> -keep class com.android.vending.billing.** //I think this may be skipped because it's already added in the library in consumer proguard file
> -keep class com.android.billingclient.api.**
> ```

I found mine is because my ProGuard does not support Java 11.

**Comment by moisoni97** [comment]
I see. Java 11 is not specifically required for this lib to work, I've just updated it to the latest version supported by Android Studio. If you can't do anything about your ProGuard, you can fork the current version of the library and compile it with any Java version that works for you then simply generate your own dependency from JitPack.

**Comment by franciscowilton** [comment]
OK thanks. Feel free to close this.

**Comment by moisoni97** [comment]
> OK thanks. Feel free to close this.

Actually, despite the fact that the library uses `Java 11`, in your project you can still use `Java 1_8` without any problems.

**Comment by franciscowilton** [comment]
> > OK thanks. Feel free to close this.
> 
> Actually, despite the fact that the library uses `Java 11`, in your project you can still use `Java 1_8` without any problems.

ProGuard has been updated in my project to a version with Java 11 support, it is now working normally.
