### ISSUE TITLE
Add method destroy billingConnector

### ISSUE THREAD

**Issue by OneDevUA** [moisoni97/google-inapp-billing#31]
Please add method to destroy billingConnector

**Comment by moisoni97** [comment]
Hi,
First of all, thanks for the suggestion!

I have added the `release()` method and it's available from the latest release `1.0.7`. The method should be use like this to avoid memory leaks:
```java
@Override
    protected void onDestroy() {
        super.onDestroy();
        if (billingConnector != null) {
            billingConnector.release();
        }
    }
```
