### ISSUE TITLE
can not restore purchase

### ISSUE THREAD

**Issue by micekeykai** [moisoni97/google-inapp-billing#35]
//            if (billingConnector.isPurchased(skuInfo) == PurchasedResult.YES) {
//                //TODO - do something  Not Work
//                Log.d("BillingConnector", "The SKU: " + skuInfo.getSku() + " is purchased");
//            } else if (billingConnector.isPurchased(skuInfo) == PurchasedResult.NO) {
//                //TODO - do something
//                Log.d("BillingConnector", "The SKU: " + skuInfo.getSku() + " is not purchased");

is purchased >>> not work，always goto >>> is not purchased。

Only way is call billingConnector.purchase(this, "sku_name");
then get error code (  ITEM_ALREADY_OWNED ) know to restore.

Do anyone have any suggestions?

Thanks。

**Comment by micekeykai** [comment]
Other solutions have been found
thank you

**Comment by moisoni97** [comment]
You can use the `onPurchasedProductsFetched` listener to check for purchased products. This is the logic you should follow:

```
            @Override
            public void onPurchasedProductsFetched(@NonNull SkuType skuType, @NonNull List<PurchaseInfo> purchases) {
                String purchasedSku;
                boolean isAcknowledged;

                for (PurchaseInfo purchaseInfo : purchases) {
                    purchasedSku = purchaseInfo.getSku();
                    isAcknowledged = purchaseInfo.isAcknowledged();

                     if (purchasedSku.equalsIgnoreCase("your_sku_id)) {
                            if (isAcknowledged) {
                                //product is purchased
                            }
                        }
                }
            }
```

**Comment by micekeykai** [comment]
Thanks。
