### ISSUE TITLE
Crash while calling connect()

### ISSUE THREAD

**Issue by sonth-bhsoft** [moisoni97/google-inapp-billing#4]
Hi, I got this error while trying to integrate your library.

`java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at games.moisoni.google_iab.BillingConnector.connect(BillingConnector.java:228)`

Can you help me?

**Comment by moisoni97** [comment]
Hi,
When creating the documentation for the library, I missed adding an important step to the wiki, but now I have updated the `README.md` file with proper information and if treated correctly this crash shouldn't happen again.

Check here what's new: https://github.com/moisoni97/google-inapp-billing#important-notice

Thanks for bringing this up!
