### ISSUE TITLE
Billing V5.0 increases apk size by 8MB compared to V4

### ISSUE THREAD

**Issue by yahlamobile** [moisoni97/google-inapp-billing#41]
Hey thanks for the update to billing V5, it works perfectly!

Just a small issue i noticed that when i use billing V5 compared to the previous V4 the size of the compiled apk is increased by approx 8mb

is anyone else having the same effect? Thanks

**Comment by moisoni97** [comment]
Hi,
Without changing anything to your app, try to build the apk again using the latest v4 version of the library, to see if the memory increase is really from here.
The library .aar file is just 61KB.

**Comment by yahlamobile** [comment]
Hi, so without changing anything within the app other then V4 and V5 billing...this is the outcome

APK with V4 - 9,140 KB
APK with V5 - 17,544 KB

**Comment by moisoni97** [comment]
Problem solved, please compile your project with the latest version: `implementation 'com.github.moisoni97:google-inapp-billing:1.1.0'`.

**Comment by yahlamobile** [comment]
Looks good!
