### ISSUE TITLE
productInfo.getPrice() is returrning Description 

### ISSUE THREAD

**Issue by thehasnism** [moisoni97/google-inapp-billing#42]
hello. thank you for such a great library. I have found an issue. In your code, instead of returning the price, it is returning the description. have a look here. 

![image](https://user-images.githubusercontent.com/52853253/189278365-420bb651-82f1-4358-8518-c061e69800e1.png)

**Comment by moisoni97** [comment]
Hi,
Thanks for the info. I'll have a look...
Apparently `getPrice()` doesn't exist anymore and I'll need to do some extra work to be able to retrieve the price.

**Comment by yahlamobile** [comment]
Here

`this.price = Objects.requireNonNull(productDetails.getOneTimePurchaseOfferDetails()).getFormattedPrice();`

**Comment by moisoni97** [comment]
Hi,
The issue is fixed. Use `getOneTimePurchaseOfferPrice()` and `getSubscriptionOfferPrice(int selectedOfferIndex, int selectedPricingPhaseIndex)` to retrieve the price.
