### ISSUE TITLE
purchase cancelled because it was not acknowledged

### ISSUE THREAD

**Issue by whoisjeeva** [moisoni97/google-inapp-billing#43]
First time using this library, I try to implement it as it says in README. but when I purchase `onProductsPurchased` was called with empty `purchases`, this is the only callback I got back.

I setup  the `billingConnector` like this.

```kotlin
billingConnector = BillingConnector(this, base64Key)
            .setConsumableIds(listOf(id1))
            .autoAcknowledge()
            .autoConsume()
            .enableLogging()
            .connect()
```

what am I missing here?

**Comment by moisoni97** [comment]
Hello,
Please share the code for the rest of the implementation.

I see you have a list of consumable products, does `onPurchaseConsumed` get called?
