### ISSUE TITLE
ImmutableList Error

### ISSUE THREAD

**Issue by DNAMobileApplications** [moisoni97/google-inapp-billing#44]
The error below keeps occurring I've searched online for a solution but nothing is working.

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/ImmutableList;
	at games.moisoni.google_iab.BillingConnector.purchase(BillingConnector.java:653)

**Comment by moisoni97** [comment]
Does implementing this `implementation 'com.google.guava:guava:31.1-android'` helps?

**Comment by DNAMobileApplications** [comment]
Yes I did end up finding that library, I'll retry later your library is perfectly structured otherwise as I'm still using the 1.0.5 version.

**Comment by moisoni97** [comment]
Is this issue solved?

**Comment by DNAMobileApplications** [comment]
> Is this issue solved?

Hey yes thank you I also figured out the issue with Subscriptions must've been on Googles end
