### ISSUE TITLE
Billing API version is not supported for the type requested

### ISSUE THREAD

**Issue by jbro129** [moisoni97/google-inapp-billing#48]
Hello, I recently tried using this library and am having some issues using it. I have one in-app purchase that I want to use your library with. The in-app is a remove ads non-consumable that would only ever be purchased once by the user (If bought in the past then I'd want the purchase to be verified and handled instead of purchased again).

Whenever I try to make a purchase I see this:

![Screenshot_20221113-194441_Google Play Store](https://user-images.githubusercontent.com/15088428/201554482-d9b9976a-b49f-4161-91b5-b846daacf0f0.jpg)

I filtered Android Studio to show me only BillingConnector: 

```
? D/BillingConnector: Billing service: connecting...
? D/BillingConnector: Billing service: connected
? D/BillingConnector: Query Product Details: data found
? D/BillingConnector: Subscriptions support check: success
? D/BillingConnector: Query SUBS Purchases: the list is empty
? D/BillingConnector: Query IN-APP Purchases: the list is empty
? D/BillingConnector: Billing API version is not supported for the type requested. Response code: 3 <-- after billingConnector.purchase
```

I followed the instruction in the readme for setting everything up.

```
implementation 'com.android.billingclient:billing:5.0.0'
implementation 'com.github.moisoni97:google-inapp-billing:1.1.1'
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
```

```
billingConnector = new BillingConnector(activity, LICENSE)
					.setNonConsumableIds(Collections.singletonList(SKU))
					.autoAcknowledge()
					.autoConsume()
					.enableLogging()
					.connect();
...

billingConnector.setBillingEventListener(new BillingEventListener() {
			@Override public void onProductsFetched(@NonNull List<ProductInfo> productDetails) {
				for (ProductInfo pinfo : productDetails)
				{
					Logd("Fetched product " + pinfo.getProductDetails().getProductId());

					...
				}
			}
			@Override public void onPurchasedProductsFetched(@NonNull ProductType productType, @NonNull List<PurchaseInfo> purchases) {
				for (PurchaseInfo pinfo : purchases)
				{
					Logd("Fetched purchased product " + pinfo.getPurchase().toString());

					...
				}
			}
			@Override public void onPurchaseConsumed(@NonNull PurchaseInfo purchase) {}

			@Override
			public void onProductsPurchased(@NonNull List<PurchaseInfo> purchases) {
				for (PurchaseInfo pinfo : purchases)
				{
					verifyPayload(pinfo.getPurchase(), new Runnable() {
						@Override
						public void run() {
							Logd("Handling purchase payload");
							
							...
						}
					});
				}
			}

			@Override
			public void onPurchaseAcknowledged(@NonNull PurchaseInfo purchase) {
				/*Callback after a purchase is acknowledged*/

				verifyPayload(purchase.getPurchase(), new Runnable() {
					@Override
					public void run() {
						Logd("Acknowledge purchase payload");
	
						...
					}
				});
			}

			@Override
			public void onBillingError(@NonNull BillingConnector billingConnector, @NonNull BillingResponse response) {

				Logd(response.toString());
			}
		});

...

billingConnector.purchase(activity, SKU); // I have this elsewhere in my code
```

I also tried updating to `com.android.billingclient:billing:5.1.0` and that didn't change anything.

Do you have any ideas why this issue is happening?

Edit:
My minSdkVersion is 23 if that helps

**Comment by newGenMobile** [comment]
? D/BillingConnector: Query SUBS Purchases: the list is empty
? D/BillingConnector: Query IN-APP Purchases: the list is empty

Do you have your billing product id set?

**Comment by jbro129** [comment]
> ? D/BillingConnector: Query SUBS Purchases: the list is empty ? D/BillingConnector: Query IN-APP Purchases: the list is empty
> 
> Do you have your billing product id set?

I have `setNonConsumableIds(Collections.singletonList(SKU))` with SKU being the the product id. 

onProductsFetched logs the product id correctly so I assumed it was fetched even though BillingConnector logged saying the lists were empty.

Should I use something other than setNonConsumableIds with the product id or should I use it with something other than Collections.singletonList?

**Comment by moisoni97** [comment]
Have you solved the issue?
