### ISSUE TITLE
Possibility to downgrade the minimum version of a package.

### ISSUE THREAD

**Issue by vitalii-vov** [moisoni97/google-inapp-billing#5]
Hello dear developer!
Can you downgrade the minimum package to Android 4.1 (API level 16)?

**Comment by moisoni97** [comment]
Hi,
Yes, I can. I'll come up with an update here to let you know when it's ready (probably today).

**Comment by moisoni97** [comment]
Hi,
I have downgraded the `minSdkVersion` to `16` to support more devices and also added new features and improvements.
To support `Android 4.1` please read the `Important notice` from `README.md`

The latest version is `implementation 'com.github.moisoni97:google-inapp-billing:1.0.2'`

If you don't have any questions on this topic please don't forget to close the issue.

**Comment by vitalii-vov** [comment]
Thank you!
