### ISSUE TITLE
Android Billing Library version 5 or newer and targeting Android 14 or higher, you must update to [PBL 5.2.1] By November 1, 2023

### ISSUE THREAD

**Issue by Kelsios** [moisoni97/google-inapp-billing#58]
I am not able to push an update on the Google Play Store, while using the latest library version 1.1.2, and targeting Android version 14 (API 34). An error message appears stating that the Google Play Billing library needs to be updated to v5.2.1 or 6.0.1 and newer. 
Could you please update?
Thanks!

**Comment by moisoni97** [comment]
Interesting since the library is already using v6.0, but will update to v6.x.x to see if it solves the issue.

**Comment by Kelsios** [comment]
Hello again,
Thanks so much for updating. However, when I use:
`implementation 'com.github.moisoni97:google-inapp-billing:1.1.3'`
I get the following error when I try to BUILD:
`Could not find com.github.moisoni97:google-inapp-billing:1.1.3.`
Is there something wrong on my end or yours?
Thanks again!

**Comment by moisoni97** [comment]
Done!
