### ISSUE TITLE
Latest Release (1.1.3) not building on JitPack.io

### ISSUE THREAD

**Issue by Kelsios** [moisoni97/google-inapp-billing#62]
Hello again,
First of all thanks for updating the library to support Android 14. 
I have tried using `implementation 'com.github.moisoni97:google-inapp-billing:1.1.3'` but, building fails since it doesn't find the library. I took a look at JitPack.io and found out that, the library itself is not building. You can take a look at the logs here:
https://jitpack.io/com/github/moisoni97/google-inapp-billing/1.1.3/build.log
I think the important part is:
```
* What went wrong:
An exception occurred applying plugin request [id: com.android.application]
 Failed to apply plugin 'com.android.internal.application'.
    Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/jdk-11
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing org.gradle.java.home` in gradle.properties.
```
Could you please take a look at the issue?
Again, thanks a lot.

**Comment by moisoni97** [comment]
Done!
