### ISSUE TITLE
License confirmation

### ISSUE THREAD

**Issue by fivedofficial** [moisoni97/google-inapp-billing#8]
As this is your code, your library and you have used Google official IAP, still we need to show a license inside our application for your Github project. Please mention your license or do we need to use it as it is without worrying about you will change the license in the future?

**Comment by moisoni97** [comment]
Hey,
I have added a `license` just for the sake of being, check it [here](https://github.com/moisoni97/google-inapp-billing/blob/master/LICENSE).
In short, you can do whatever you want with this library, except for `trademark use`.

**Comment by fivedofficial** [comment]
Thank you very much, when I used this library will let you know if faced any bugs :)
