### ISSUE TITLE
No billing events triggered if one of the sku Id lists are empty

### ISSUE THREAD

**Issue by ay1man4** [moisoni97/google-inapp-billing#9]
Hi,

Thank you for this easy to use and updated library.
I followed implementation guide. Billing service is connected but I did not receive any events like "onProductsFetched" **if one of the provide sku Id lists is empty.**

**Use case:**

- App query SKU ID List (Consumable, Non-Consumbable and Subscription) automatically from a web service.
- App sets SUK ID lists during connecting to billing service, _see below code_.
- Later, developer decided to drop one kind of subsriptions, for example Consumable. So, App will not receive this list, it will be empty.

I think above scenarion should be considered since some developers doesn't like to hardcode SKU ID's as it subject to change. Hardcoding SKU ID means new App releasing on every change.

Below are some code snapshots:

```
        billingConnector = BillingConnector(this, licenseKey)
            .setNonConsumableIds(nonConsumableIds)
            .setConsumableIds(consumableIds)
            .setSubscriptionIds(subscriptionIds)
            .autoAcknowledge()
            .autoConsume()
            .enableLogging()
            .connect()
```

In my case:
nonConsumableIds, subscriptionIds have some items _but consumableIds is empty list._

```
        billingConnector.setBillingEventListener(object : BillingEventListener {
            override fun onProductsFetched(skuDetails: MutableList<SkuInfo>) {

                skuDetailsList.addAll(skuDetails)
                adapter.notifyDataSetChanged()
                
                progress.visibility = View.GONE
            }
```

In manifest:
`<uses-permission android:name="com.android.vending.BILLING" />`

Below are the only billing logs received:

```
D/BillingConnector: Billing service: connecting...
D/BillingConnector: Billing service: connected
```

Thanks,

**Comment by moisoni97** [comment]
I don't see why would you want to update the SKU ids from a web service, because you'll have to release a new version of the app anyway to update the UI or the app's functionality accordingly to the missing SKU. If you simply don't want an SKU mark it as `inactive` in Play Console. I think updating the SKUs from a `web service` is overkill.

Anyway if you say that setting an `empty list` result in events not being triggered, is a problem and I will check.

**Comment by ay1man4** [comment]
In many apps, you may need to add some new kind of coins from time to time without need to release for example adding paid  chrachters' styles, lower or higher balance purchases depends on users' purchase analysis, or deciding to remove a product as most users doesn't like it. 
Such change may not require UI change as it already considered in UI design to be presented in list. 

So, Yes in some cases, updating purchases does'nt require new release, so this issue may occurs.

**Comment by moisoni97** [comment]
I still don't have enough free time to work on this, if it's urgent to you, please make a PR

**Comment by moisoni97** [comment]
Finally, I had some time to work on this but unfortunately, I can not replicate your issue,
Are you sure it doesn't have anything to do with your implementation?

Since it's an old issue I will close, feel free to re-open it if you haven't already solved the problem.
